title: Juanma Pérez Rabasco <hello@juanma.xyz>
email: hello@juanma.xyz
description: >-
  I write [code],
  make things with pixels,
  and tweak systems.
baseurl: ""
url: "https://juanma.xyz"
github:
  repo:  https://github.com/aikijuanma/juanma.xyz
timezone: Europe/Madrid
markdown: kramdown
