title: Juanma Pérez Rabasco <hello@juanma.xyz>
email: hello@juanma.xyz
description: >-
  I write [code],
  make things with pixels,
  and tweak systems.
baseurl: ""
url: "https://juanma.xyz"
github:
  repo:  https://github.com/aikijuanma/juanma.xyz
timezone: Europe/Madrid
markdown: kramdown

exclude:
  - node_modules
  - _includes/cssrelpreload.js
  - scripts/all.js
  - scripts/default.js
  - scripts/jquery-3.3.1.slim.js
  - styles/base.less
  - styles/default.less
  - gulpfile.js
  - package-lock.json
  - package.json
